# Generated by Django 5.2.8 on 2025-11-08 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='mentee', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill_level', models.CharField(blank=True, max_length=50)),
                ('areas_of_interest', models.TextField(blank=True, help_text='Comma-separated interests')),
                ('expertise', models.TextField(blank=True, help_text='Comma-separated expertise areas')),
                ('years_experience', models.IntegerField(blank=True, default=0)),
                ('availability', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
